get:
  description: List the settings.
  operationId: getSettings
  parameters:
    - $ref: '../../openapi.yaml#/components/parameters/Limit'
    - $ref: '../../openapi.yaml#/components/parameters/Offset'
    - $ref: '../../openapi.yaml#/components/parameters/Single'
    - $ref: '../../openapi.yaml#/components/parameters/Meta'
    - $ref: '../../openapi.yaml#/components/parameters/Page'
  responses:
    '200':
      description: Successful request
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: '../../openapi.yaml#/components/schemas/Setting'
    '401':
      $ref: '../../openapi.yaml#/components/responses/UnauthorizedError'        
    '404':
      $ref: '../../openapi.yaml#/components/responses/NotFoundError'
  tags:
  - Settings
patch:
  description: Update an existing setting
  operationId: updateSetting
  requestBody:
    content:
      application/json:
        schema:
          type: object
  responses:
    '200':
      description: Successful request
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: '../../openapi.yaml#/components/schemas/Setting'
    '401':
      $ref: '../../openapi.yaml#/components/responses/UnauthorizedError'
    '404':
      $ref: '../../openapi.yaml#/components/responses/NotFoundError'
  tags:
  - Settings
# post:
#   description: Create a new setting.
#   operationId: createSettings
#   parameters:
#     - $ref: '../../openapi.yaml#/components/parameters/Meta'
#   requestBody:
#     content:
#       application/json:
#         schema:
#           type: object
#   responses:
#     '200':
#       description: Successful request
#       content:
#         application/json:
#           schema:
#             type: object
#             properties:
#               data:
#                 $ref: '../../openapi.yaml#/components/schemas/Setting'
#     '401':
#       $ref: '../../openapi.yaml#/components/responses/UnauthorizedError'
#     '404':
#       $ref: '../../openapi.yaml#/components/responses/NotFoundError'
#   tags:
#   - Settings